server:
  port: 8080

spring:
  application:
    name: weather-aggregator-server
  datasource:
    url: jdbc:postgresql://localhost:5432/weather_aggregator
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    schemas: weather_aggregator

logging:
  level:
    root: INFO

executor:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 100
  thread-name-prefix: "WeatherThread-"

weather-aggregator:
  number-of-sources: 100
